config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
require 'api/api'

Rails.application.routes.draw do
  if Gitlab::Sherlock.enabled?
    namespace :sherlock do
      resources :transactions, only: [:index, :show] do
        resources :queries, only: [:show]
        resources :file_samples, only: [:show]

        collection do
          delete :destroy_all
        end
      end
    end
  end

  namespace :ci do
    # CI API
    Ci::API::API.logger Rails.logger
    mount Ci::API::API => '/api'

    resource :lint, only: [:show, :create]

    resources :projects do
      member do
        get :status, to: 'projects#badge'
        get :integration
      end
    end

    root to: 'projects#index'
  end

  use_doorkeeper do
    controllers applications: 'oauth/applications',
                authorized_applications: 'oauth/authorized_applications',
                authorizations: 'oauth/authorizations'
  end

  # Autocomplete
  get '/autocomplete/users' => 'autocomplete#users'
  get '/autocomplete/users/:id' => 'autocomplete#user'


  # Search
  get 'search' => 'search#show'
  get 'search/autocomplete' => 'search#autocomplete', as: :search_autocomplete

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  constraint = lambda { |request| request.env['warden'].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: '/admin/sidekiq', as: :sidekiq
  end

  # Enable Grack support
  mount Grack::AuthSpawner, at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }, via: [:get, :post, :put]

  # Help
  get 'help'                  => 'help#index'
  get 'help/:category/:file'  => 'help#show', as: :help_page, constraints: { category: /.*/, file: /[^\/\.]+/ }
  get 'help/shortcuts'
  get 'help/ui'               => 'help#ui'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get 'raw'
    end
  end

  get '/s/:username' => 'snippets#index', as: :user_snippets, constraints: { username: /.*/ }

  #
  # Invites
  #

  resources :invites, only: [:show], constraints: { id: /[A-Za-z0-9_-]+/ } do
    member do
      post :accept
      match :decline, via: [:get, :post]
    end
  end

  resources :sent_notifications, only: [], constraints: { id: /\h{32}/ } do
    member do
      get :unsubscribe
    end
  end

  # Spam reports
  resources :abuse_reports, only: [:new, :create]

  #
  # Import
  #
  namespace :import do
    resource :github, only: [:create, :new], controller: :github do
      get :status
      get :callback
      get :jobs
    end

    resource :gitlab, only: [:create, :new], controller: :gitlab do
      get :status
      get :callback
      get :jobs
    end

    resource :bitbucket, only: [:create, :new], controller: :bitbucket do
      get :status
      get :callback
      get :jobs
    end

    resource :gitorious, only: [:create, :new], controller: :gitorious do
      get :status
      get :callback
      get :jobs
    end

    resource :google_code, only: [:create, :new], controller: :google_code do
      get :status
      post :callback
      get :jobs

      get   :new_user_map,    path: :user_map
      post  :create_user_map, path: :user_map
    end

    resource :fogbugz, only: [:create, :new], controller: :fogbugz do
      get :status
      post :callback
      get :jobs

      get   :new_user_map,    path: :user_map
      post  :create_user_map, path: :user_map
    end
  end

  #
  # Uploads
  #

  scope path: :uploads do
    # Note attachments and User/Group/Project avatars
    get ":model/:mounted_as/:id/:filename",
        to:           "uploads#show",
        constraints:  { model: /note|user|group|project/, mounted_as: /avatar|attachment/, filename: /[^\/]+/ }

    # Project markdown uploads
    get ":namespace_id/:project_id/:secret/:filename",
      to:           "projects/uploads#show",
      constraints:  { namespace_id: /[a-zA-Z.0-9_\-]+/, project_id: /[a-zA-Z.0-9_\-]+/, filename: /[^\/]+/ }
  end

  # Redirect old note attachments path to new uploads path.
  get "files/note/:id/:filename",
    to:           redirect("uploads/note/attachment/%{id}/%{filename}"),
    constraints:  { filename: /[^\/]+/ }

  #
  # Explore area
  #
  namespace :explore do
    resources :projects, only: [:index] do
      collection do
        get :trending
        get :starred
      end
    end

    resources :groups, only: [:index]
    resources :snippets, only: [:index]
    root to: 'projects#trending'
  end

  # Compatibility with old routing
  get 'public' => 'explore/projects#index'
  get 'public/projects' => 'explore/projects#index'

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      resources :keys, only: [:show, :destroy]
      resources :identities, except: [:show]

      delete 'stop_impersonation' => 'impersonation#destroy', on: :collection

      member do
        get :projects
        get :keys
        get :groups
        put :team_update
        put :block
        put :unblock
        put :unlock
        put :confirm
        post 'impersonate' => 'impersonation#create'
        patch :disable_two_factor
        delete 'remove/:email_id', action: 'remove_email', as: 'remove_email'
      end
    end

    resources :abuse_reports, only: [:index, :destroy]
    resources :applications

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :members_update
      end
    end

    resources :deploy_keys, only: [:index, :new, :create, :destroy]

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resources :broadcast_messages, only: [:index, :edit, :create, :update, :destroy]
    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]

    resources :namespaces, path: '/projects', constraints: { id: /[a-zA-Z.0-9_\-]+/ }, only: [] do
      root to: 'projects#index', as: :projects

      resources(:projects,
                path: '/',
                constraints: { id: /[a-zA-Z.0-9_\-]+/ },
                only: [:index, :show]) do
        root to: 'projects#show'

        member do
          put :transfer
        end

        resources :runner_projects
      end
    end

    resource :application_settings, only: [:show, :update] do
      resources :services
      put :reset_runners_token
    end

    resources :labels

    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        get :resume
        get :pause
      end
    end

    resources :builds, only: :index do
      collection do
        post :cancel_all
      end
    end

    root to: 'dashboard#index'
  end

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :audit_log
      get :applications

      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :account, only: [:show, :update] do
        member do
          delete :unlink
        end
      end
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create, :edit, :update] do
        member do
          put :reset
        end
      end
      resource :preferences, only: [:show, :update]
      resources :keys
      resources :emails, only: [:index, :create, :destroy]
      resource :avatar, only: [:destroy]
      resource :two_factor_auth, only: [:new, :create, :destroy] do
        member do
          post :codes
          patch :skip
        end
      end
    end
  end

  get 'u/:username/calendar' => 'users#calendar', as: :user_calendar,
      constraints: { username: /.*/ }

  get 'u/:username/calendar_activities' => 'users#calendar_activities', as: :user_calendar_activities,
      constraints: { username: /.*/ }

  get '/u/:username' => 'users#show', as: :user,
      constraints: { username: /[a-zA-Z.0-9_\-]+(?<!\.atom)/ }

  #
  # Dashboard Area
  #
  resource :dashboard, controller: 'dashboard', only: [] do
    get :issues
    get :merge_requests
    get :activity

    scope module: :dashboard do
      resources :milestones, only: [:index, :show]

      resources :groups, only: [:index]
      resources :snippets, only: [:index]

      resources :projects, only: [:index] do
        collection do
          get :starred
        end
      end
    end

    root to: "dashboard/projects#index"
  end

  #
  # Groups Area
  #
  resources :groups, constraints: { id: /[a-zA-Z.0-9_\-]+(?<!\.atom)/ }  do
    member do
      get :issues
      get :merge_requests
      get :projects
    end

    scope module: :groups do
      resources :group_members, only: [:index, :create, :update, :destroy] do
        post :resend_invite, on: :member
        delete :leave, on: :collection
      end

      resource :avatar, only: [:destroy]
      resources :milestones, constraints: { id: /[^\/]+/ }, only: [:index, :show, :update, :new, :create]
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:index, :new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations , passwords: :passwords, sessions: :sessions, confirmations: :confirmations }

  devise_scope :user do
    get '/users/auth/:provider/omniauth_error' => 'omniauth_callbacks#omniauth_error', as: :omniauth_error
  end

  root to: "root#index"

  #
  # Project Area
  #
  resources :namespaces, path: '/', constraints: { id: /[a-zA-Z.0-9_\-]+/ }, only: [] do
    resources(:projects, constraints: { id: /[a-zA-Z.0-9_\-]+(?<!\.atom)/ }, except:
              [:new, :create, :index], path: "/") do
      member do
        put :transfer
        delete :remove_fork
        post :archive
        post :unarchive
        post :housekeeping
        post :toggle_star
        post :markdown_preview
        get :autocomplete_sources
        get :activity
      end

      scope module: :projects do
        # Blob routes:

app/controllers/import/base_controller.rb
class Import::BaseController < ApplicationController

  private

  def get_or_create_namespace
    begin
      namespace = Group.create!(name: @target_namespace, path: @target_namespace, owner: current_user)
      namespace.add_owner(current_user)
    rescue ActiveRecord::RecordNotUnique, ActiveRecord::RecordInvalid
      namespace = Namespace.find_by_path_or_name(@target_namespace)
      unless current_user.can?(:create_projects, namespace)
        @already_been_taken = true
        return false
      end
    end

    namespace
  end
end

app/controllers/import/bitbucket_controller.rb
class Import::BitbucketController < Import::BaseController
  before_action :verify_bitbucket_import_enabled
  before_action :bitbucket_auth, except: :callback

  rescue_from OAuth::Error, with: :bitbucket_unauthorized
  rescue_from Gitlab::BitbucketImport::Client::Unauthorized, with: :bitbucket_unauthorized

  def callback
    request_token = session.delete(:oauth_request_token)
    raise "Session expired!" if request_token.nil?

    request_token.symbolize_keys!

    access_token = client.get_token(request_token, params[:oauth_verifier], callback_import_bitbucket_url)

    session[:bitbucket_access_token] = access_token.token
    session[:bitbucket_access_token_secret] = access_token.secret

    redirect_to status_import_bitbucket_url
  end

  def status
    @repos = client.projects
    @incompatible_repos = client.incompatible_projects

    @already_added_projects = current_user.created_projects.where(import_type: "bitbucket")
    already_added_projects_names = @already_added_projects.pluck(:import_source)

    @repos.to_a.reject!{ |repo| already_added_projects_names.include? "#{repo["owner"]}/#{repo["slug"]}" }
  end

  def jobs
    jobs = current_user.created_projects.where(import_type: "bitbucket").to_json(only: [:id, :import_status])
    render json: jobs
  end

  def create
    @repo_id = params[:repo_id] || ""
    repo = client.project(@repo_id.gsub("___", "/"))
    @project_name = repo["slug"]

    repo_owner = repo["owner"]
    repo_owner = current_user.username if repo_owner == client.user["user"]["username"]
    @target_namespace = params[:new_namespace].presence || repo_owner

    namespace = get_or_create_namespace || (render and return)

    unless Gitlab::BitbucketImport::KeyAdder.new(repo, current_user, access_params).execute
      @access_denied = true
      render
      return
    end

    @project = Gitlab::BitbucketImport::ProjectCreator.new(repo, namespace, current_user, access_params).execute
  end

  private

  def client
    @client ||= Gitlab::BitbucketImport::Client.new(session[:bitbucket_access_token],
                                                    session[:bitbucket_access_token_secret])
  end

  def verify_bitbucket_import_enabled
    render_404 unless bitbucket_import_enabled?
  end

  def bitbucket_auth
    if session[:bitbucket_access_token].blank?
      go_to_bitbucket_for_permissions
    end
  end

  def go_to_bitbucket_for_permissions
    request_token = client.request_token(callback_import_bitbucket_url)
    session[:oauth_request_token] = request_token

    redirect_to client.authorize_url(request_token, callback_import_bitbucket_url)
  end

  def bitbucket_unauthorized
    go_to_bitbucket_for_permissions
  end

  private

  def access_params
    {
      bitbucket_access_token: session[:bitbucket_access_token],
      bitbucket_access_token_secret: session[:bitbucket_access_token_secret]
    }
  end
end

app/controllers/import/fogbugz_controller.rb
class Import::FogbugzController < Import::BaseController
  before_action :verify_fogbugz_import_enabled
  before_action :user_map, only: [:new_user_map, :create_user_map]

  rescue_from Fogbugz::AuthenticationException, with: :fogbugz_unauthorized

  def new

  end

  def callback
    begin
      res = Gitlab::FogbugzImport::Client.new(import_params.symbolize_keys)
    rescue
      # If the URI is invalid various errors can occur
      return redirect_to new_import_fogbugz_path, alert: 'Could not connect to FogBugz, check your URL'
    end
    session[:fogbugz_token] = res.get_token
    session[:fogbugz_uri] = params[:uri]

    redirect_to new_user_map_import_fogbugz_path
  end

  def new_user_map

  end

  def create_user_map
    user_map = params[:users]

    unless user_map.is_a?(Hash) && user_map.all? { |k, v| !v[:name].blank? }
      flash.now[:alert] = 'All users must have a name.'

      render 'new_user_map' and return
    end

    session[:fogbugz_user_map] = user_map

    flash[:notice] = 'The user map has been saved. Continue by selecting the projects you want to import.'

    redirect_to status_import_fogbugz_path
  end

  def status
    unless client.valid?
      return redirect_to new_import_fogbugz_path
    end

    @repos = client.repos

    @already_added_projects = current_user.created_projects.where(import_type: 'fogbugz')
    already_added_projects_names = @already_added_projects.pluck(:import_source)

    @repos.reject! { |repo| already_added_projects_names.include? repo.name }
  end

  def jobs
    jobs = current_user.created_projects.where(import_type: 'fogbugz').to_json(only: [:id, :import_status])
    render json: jobs
  end

  def create
    @repo_id = params[:repo_id]
    repo = client.repo(@repo_id)
    fb_session = { uri: session[:fogbugz_uri], token: session[:fogbugz_token] }
    @target_namespace = current_user.namespace
    @project_name = repo.name

    namespace = @target_namespace

    umap = session[:fogbugz_user_map] || client.user_map

    @project = Gitlab::FogbugzImport::ProjectCreator.new(repo, fb_session, namespace, current_user, umap).execute
  end

  private

  def client
    @client ||= Gitlab::FogbugzImport::Client.new(token: session[:fogbugz_token], uri: session[:fogbugz_uri])
  end

  def user_map
    @user_map ||= begin
      user_map = client.user_map

      stored_user_map = session[:fogbugz_user_map]
      user_map.update(stored_user_map) if stored_user_map

      user_map
    end
  end

  def fogbugz_unauthorized(exception)
    redirect_to new_import_fogbugz_path, alert: exception.message
  end

  def import_params
    params.permit(:uri, :email, :password)
  end

  def verify_fogbugz_import_enabled
    render_404 unless fogbugz_import_enabled?
  end
end

app/controllers/import/gitorious_controller.rb
class Import::GitoriousController < Import::BaseController
  before_action :verify_gitorious_import_enabled

  def new
    redirect_to client.authorize_url(callback_import_gitorious_url)
  end

  def callback
    session[:gitorious_repos] = params[:repos]
    redirect_to status_import_gitorious_path
  end

  def status
    @repos = client.repos

    @already_added_projects = current_user.created_projects.where(import_type: "gitorious")
    already_added_projects_names = @already_added_projects.pluck(:import_source)

    @repos.reject! { |repo| already_added_projects_names.include? repo.full_name }
  end

  def jobs
    jobs = current_user.created_projects.where(import_type: "gitorious").to_json(only: [:id, :import_status])
    render json: jobs
  end

  def create
    @repo_id = params[:repo_id]
    repo = client.repo(@repo_id)
    @target_namespace = params[:new_namespace].presence || repo.namespace
    @project_name = repo.name

    namespace = get_or_create_namespace || (render and return)

    @project = Gitlab::GitoriousImport::ProjectCreator.new(repo, namespace, current_user).execute
  end

  private

  def client
    @client ||= Gitlab::GitoriousImport::Client.new(session[:gitorious_repos])
  end

  def verify_gitorious_import_enabled
    render_404 unless gitorious_import_enabled?
  end

end

app/views/import/google_code/new.html.haml
- page_title "Google Code import"
- header_title "Projects", root_path
%h3.page-title
  %i.fa.fa-google
  Import projects from Google Code
%hr

= form_tag callback_import_google_code_path, class: 'form-horizontal', multipart: true do
  %p
    Follow the steps below to export your Google Code project data.
    In the next step, you'll be able to select the projects you want to import.
  %ol
    %li
      %p
        Go to
        #{link_to "Google Takeout", "https://www.google.com/settings/takeout", target: "_blank"}.
    %li
      %p
        Make sure you're logged into the account that owns the projects you'd like to import.
    %li
      %p
        Click the <strong>Select none</strong> button on the right, since we only need "Google Code Project Hosting".
    %li
      %p
        Scroll down to <strong>Google Code Project Hosting</strong> and enable the switch on the right.
    %li
      %p
        Choose <strong>Next</strong> at the bottom of the page.
    %li
      %p
        Leave the "File type" and "Delivery method" options on their default values.
    %li
      %p
        Choose <strong>Create archive</strong> and wait for archiving to complete.
    %li
      %p
        Click the <strong>Download</strong> button and wait for downloading to complete.
    %li
      %p
        Find the downloaded ZIP file and decompress it.
    %li
      %p
        Find the newly extracted <code>Takeout/Google Code Project Hosting/GoogleCodeProjectHosting.json</code> file.
    %li
      %p
        Upload <code>GoogleCodeProjectHosting.json</code> here:
      %p
        %input{type: "file", name: "dump_file", id: "dump_file"}
    %li
      %p
        Do you want to customize how Google Code email addresses and usernames are imported into GitLab?
      %p
        = label_tag :create_user_map_0 do
          = radio_button_tag :create_user_map, 0, true
          No, directly import the existing email addresses and usernames.
      %p
        = label_tag :create_user_map_1 do
          = radio_button_tag :create_user_map, 1, false
          Yes, let me map Google Code users to full names or GitLab users.
    %li
      %p
        = submit_tag 'Continue to the next step', class: "btn btn-create"

app/views/import/google_code/new_user_map.html.haml
- page_title "User map", "Google Code import"
- header_title "Projects", root_path
%h3.page-title
  %i.fa.fa-google
  Import projects from Google Code
%hr

= form_tag create_user_map_import_google_code_path, class: 'form-horizontal' do
  %p
    Customize how Google Code email addresses and usernames are imported into GitLab.
    In the next step, you'll be able to select the projects you want to import.
  %p
    The user map is a JSON document mapping the Google Code users that participated on your projects to the way their email addresses and usernames will be imported into GitLab. You can change this by changing the value on the right hand side of <code>:</code>. Be sure to preserve the surrounding double quotes, other punctuation and the email address or username on the left hand side.
  %ul
    %li
      %strong Default: Directly import the Google Code email address or username
      %p
        <code>"johnsmith@example.com": "johnsm...@example.com"</code>
        will add "By johnsm...@example.com" to all issues and comments originally created by johnsmith@example.com.
        The email address or username is masked to ensure the user's privacy.
    %li
      %strong Map a Google Code user to a GitLab user
      %p
        <code>"johnsmith@example.com": "@johnsmith"</code>
        will add "By <a href="#">@johnsmith</a>" to all issues and comments originally created by johnsmith@example.com,
        and will set <a href="#">@johnsmith</a> as the assignee on all issues originally assigned to johnsmith@example.com.
    %li
      %strong Map a Google Code user to a full name
      %p
        <code>"johnsmith@example.com": "John Smith"</code>
        will add "By John Smith" to all issues and comments originally created by johnsmith@example.com.
    %li
      %strong Map a Google Code user to a full email address
      %p
        <code>"johnsmith@example.com": "johnsmith@example.com"</code>
        will add "By <a href="#">johnsmith@example.com</a>" to all issues and comments originally created by johnsmith@example.com.
        By default, the email address or username is masked to ensure the user's privacy. Use this option if you want to show the full email address.

  .form-group
    .col-sm-12
      = text_area_tag :user_map, JSON.pretty_generate(@user_map), class: 'form-control', rows: 15

  .form-actions
    = submit_tag 'Continue to the next step', class: "btn btn-create"

app/views/import/google_code/status.html.haml
- page_title "Google Code import"
- header_title "Projects", root_path
%h3.page-title
  %i.fa.fa-google
  Import projects from Google Code

- if @repos.any?
  %p.light
    Select projects you want to import.
  %p.light
    Optionally, you can
    = link_to "customize", new_user_map_import_google_code_path
    how Google Code email addresses and usernames are imported into GitLab.
  %hr
  %p
  - if @incompatible_repos.any?
    = button_tag 'Import all compatible projects', class: "btn btn-success js-import-all"
  - else
    = button_tag 'Import all projects', class: "btn btn-success js-import-all"

.table-holder
  %table.table.import-jobs
    %thead
      %tr
        %th From Google Code
        %th To GitLab
        %th Status
    %tbody
      - @already_added_projects.each do |project|
        %tr{id: "project_#{project.id}", class: "#{project_status_css_class(project.import_status)}"}
          %td
            = link_to project.import_source, "https://code.google.com/p/#{project.import_source}", target: "_blank"
          %td
            %strong= link_to project.path_with_namespace, [project.namespace.becomes(Namespace), project]
          %td.job-status
            - if project.import_status == 'finished'
              %span
                %i.fa.fa-check
                done
            - elsif project.import_status == 'started'
              %i.fa.fa-spinner.fa-spin
              started
            - else
              = project.human_import_status_name

      - @repos.each do |repo|
        %tr{id: "repo_#{repo.id}"}
          %td
            = link_to repo.name, "https://code.google.com/p/#{repo.name}", target: "_blank"
          %td.import-target
            = "#{current_user.username}/#{repo.name}"
          %td.import-actions.job-status
            = button_tag "Import", class: "btn js-add-to-import"
      - @incompatible_repos.each do |repo|
        %tr{id: "repo_#{repo.id}"}
          %td
            = link_to repo.name, "https://code.google.com/p/#{repo.name}", target: "_blank"
          %td.import-target
          %td.import-actions-job-status
            = label_tag "Incompatible Project", nil, class: "label label-danger"

- if @incompatible_repos.any?
  %p
    One or more of your Google Code projects cannot be imported into GitLab
    directly because they use Subversion or Mercurial for version control,
    rather than Git. Please convert them to Git on Google Code, and go
    through the
    = link_to "import flow", new_import_google_code_path
    again.

:javascript
  new ImporterStatus("#{jobs_import_google_code_path}", "#{import_google_code_path}");